name: Close Asana task after PR merged

on:
    pull_request:
        types: [closed]

jobs:
    add-merged-comment:
        if: contains(join(github.event.pull_request.labels.*.name, ','), 'SBT-PFM')
        runs-on: ubuntu-latest
        steps:
            - name: Get task IDs in PR
              uses: duckduckgo/native-github-asana-sync@v2.0
              id: find-asana-task-ids
              with:
                  action: 'find-asana-task-ids'

            - name: Close Asana task on merge
              uses: duckduckgo/native-github-asana-sync@v2.0
              if: github.event.pull_request.merged == true
              with:
                  asana-pat: ${{ secrets.ASANA_ACCESS_TOKEN }}
                  asana-task-id: '${{ steps.find-asana-task-ids.outputs.asanaTaskIds }}'
                  is-complete: true
                  action: 'notify-pr-merged'
