name: PFM PR Opened|Reopened

on:
    pull_request:
        types: [opened, reopened]

jobs:
    link-pfm-pr:
        if: contains(join(github.event.pull_request.labels.*.name, ','), 'SBT-PFM')
        runs-on: ubuntu-latest
        steps:
            - name: Get task IDs in PR
              uses: ./actions
              id: find-asana-task-ids
              with:
                  action: 'find-asana-task-ids'

            - name: Add PR link to Asana
              uses: duckduckgo/native-github-asana-sync@v2.0
              with:
                  asana-pat: ${{ secrets.ASANA_ACCESS_TOKEN }}
                  asana-task-id: '${{ steps.find-asana-task-ids.outputs.asanaTaskIds }}'
                  is-pinned: true
                  action: 'add-asana-comment'
