name: PFM Asana Integration

on:
    pull_request:
        types: [opened, reopened, closed]
    pull_request_review:
        types: [submitted]

jobs:
    # Handle PR opened/reopened
    link-pfm-pr:
        if: |
            github.event_name == 'pull_request' && 
            (contains(github.event.action, 'opened') || contains(github.event.action, 'reopened')) &&
            contains(join(github.event.pull_request.labels.*.name, ','), 'SBT-PFM')
        runs-on: ubuntu-latest
        steps:
            - name: Get task IDs in PR
              uses: duckduckgo/native-github-asana-sync@v2.1
              id: find-asana-task-ids
              with:
                  action: 'find-asana-task-ids'

            - name: Add PR link to Asana
              uses: duckduckgo/native-github-asana-sync@v2.1
              with:
                  asana-pat: ${{ secrets.ASANA_ACCESS_TOKEN }}
                  asana-task-id: '${{ steps.find-asana-task-ids.outputs.asanaTaskIds }}'
                  is-pinned: true
                  action: 'add-asana-comment'

    # Handle PR merged
    add-pr-merged-comment:
        if: |
            github.event_name == 'pull_request' && 
            github.event.action == 'closed' &&
            github.event.pull_request.merged == true &&
            contains(join(github.event.pull_request.labels.*.name, ','), 'SBT-PFM')
        runs-on: ubuntu-latest
        steps:
            - name: Get task IDs in PR
              uses: duckduckgo/native-github-asana-sync@v2.1
              id: find-asana-task-ids
              with:
                  action: 'find-asana-task-ids'

            - name: Close Asana task on merge
              uses: duckduckgo/native-github-asana-sync@v2.1
              with:
                  asana-pat: ${{ secrets.ASANA_ACCESS_TOKEN }}
                  asana-task-id: '${{ steps.find-asana-task-ids.outputs.asanaTaskIds }}'
                  is-complete: true
                  action: 'notify-pr-merged'

    # Handle PR reviews
    pr-reviewed:
        if: |
            github.event_name == 'pull_request_review' &&
            contains(join(github.event.pull_request.labels.*.name, ','), 'SBT-PFM')
        runs-on: ubuntu-latest
        steps:
            - name: Get task IDs in PR
              uses: duckduckgo/native-github-asana-sync@v2.1
              id: find-asana-task-ids
              with:
                  action: 'find-asana-task-ids'

            - name: Notify PR approved in Asana
              if: github.event.review.state == 'approved'
              uses: duckduckgo/native-github-asana-sync@v2.1
              with:
                  asana-pat: ${{ secrets.ASANA_ACCESS_TOKEN }}
                  asana-task-id: '${{ steps.find-asana-task-ids.outputs.asanaTaskIds }}'
                  asana-task-comment: 'PR: ${{ github.event.pull_request.html_url }} has been approved.'
                  asana-task-comment-pinned: true
                  action: 'post-comment-asana-task'

            - name: Notify changes requested in Asana
              if: github.event.review.state == 'changes_requested'
              uses: duckduckgo/native-github-asana-sync@v2.1
              with:
                  asana-pat: ${{ secrets.ASANA_ACCESS_TOKEN }}
                  asana-task-id: '${{ steps.find-asana-task-ids.outputs.asanaTaskIds }}'
                  asana-task-comment: 'Changes requested on PR: ${{ github.event.pull_request.html_url }}'
                  asana-task-comment-pinned: false
                  action: 'post-comment-asana-task'

            - name: Add PR comment to Asana
              if: github.event.review.state == 'commented'
              uses: duckduckgo/native-github-asana-sync@v2.1
              with:
                  asana-pat: ${{ secrets.ASANA_ACCESS_TOKEN }}
                  asana-task-id: '${{ steps.find-asana-task-ids.outputs.asanaTaskIds }}'
                  asana-task-comment: 'PR: ${{ github.event.pull_request.html_url }} has a new comment.'
                  asana-task-comment-pinned: false
                  action: 'post-comment-asana-task'
